auto_restart: true
auto_tasks: false
battle_stratege: normal
battle_time_wait: 1
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_battle_stratege: kill_big
boss_hero:
  BARL_008H:
  - "\u7A46\u5766\u52AA\u65AF"
  - Mutanus
  - 1, 2, 3
  - 1
  - '2'
  LETL_005H:
  - "\u7C73\u5C14\u8C6A\u65AF\xB7\u6CD5\u529B\u98CE\u66B4"
  - Millhouse Manastorm
  - 1, 2, 3
  - 0
  - '1'
  LETL_009H:
  - "\u683C\u7F57\u739B\u4EC0\xB7\u5730\u72F1\u5486\u54EE"
  - Grommash Hellscream
  - 1, 2, 3
  - 2
  - '3'
  LETL_033H:
  - "\u683C\u9C81\u5C14"
  - Gruul
  - 1, 2, 3
  - 4
  - '3'
  LETL_040H:
  - "\u5854\u59C6\u8F9B\xB7\u7F57\u59C6"
  - Tamsin Roame
  - 1, 2, 3
  - 5
  - '1'
  SWL_06H:
  - "\u8003\u5185\u7559\u65AF\xB7\u7F57\u59C6"
  - Cornelius Roame
  - 1, 2, 3
  - 3
  - '3'
boss_id: '1'
choice_skill_index: 0
confidence: 0.8
delay: 1
early_stop: false
fix_x: 0
fix_y: 0
hero:
  BARL_008H:
  - "\u7A46\u5766\u52AA\u65AF"
  - Mutanus
  - 1, 2, 3
  - 1
  - '2'
  LETL_005H:
  - "\u7C73\u5C14\u8C6A\u65AF\xB7\u6CD5\u529B\u98CE\u66B4"
  - Millhouse Manastorm
  - 1, 2, 3
  - 0
  - '1'
  LETL_009H:
  - "\u683C\u7F57\u739B\u4EC0\xB7\u5730\u72F1\u5486\u54EE"
  - Grommash Hellscream
  - 1, 2, 3
  - 2
  - '3'
  LETL_033H:
  - "\u683C\u9C81\u5C14"
  - Gruul
  - 1, 2, 3
  - 4
  - '3'
  LETL_040H:
  - "\u5854\u59C6\u8F9B\xB7\u7F57\u59C6"
  - Tamsin Roame
  - 1, 2, 3
  - 5
  - '1'
  SWL_06H:
  - "\u8003\u5185\u7559\u65AF\xB7\u7F57\u59C6"
  - Cornelius Roame
  - 1, 2, 3
  - 3
  - '3'
hs_log: C:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: C:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: ZH-1600x900
lettuce_role_limit: '5'
longest_waiting: 80
map_decision: visitor_first
reward_count_dropdown: '3'
screenshot_error: true
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
stop_at_boss: false
team_id: 1
ui_lang: chs
